export const FETCH_CUST_ADDRESS_REQUEST = 'FETCH_CUST_ADDRESS_REQUEST';
export const FETCH_CUST_ADDRESS_SUCCESS = 'FETCH_CUST_ADDRESS_SUCCESS';
export const FETCH_CUST_ADDRESS_FAILURE = 'FETCH_CUST_ADDRESS_FAILURE';